name: readme CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t readme .
      - name: Tags
        run: |
          docker tag readme ${{ secrets.DOCKER_USER }}/readme:${{ github.sha }}
          docker tag readme ${{ secrets.DOCKER_USER }}/readme:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/readme:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/readme:latest
